name: IT Change
description: File an IT change request.
title: "[IT Change]: "
labels: ["change"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - showoffninja
body:
  - type: textarea
    id: Introduction
    attributes:
      label: Describe the change you are requesting.
      description: What is the change you are requesting?
      placeholder: Describe the change you are requesting.
    validations:
      required: true
  - type: markdown
    id: assessment
    attributes:
      value: |
      "## Assessments"
      
      "Determine if IT QA approval of implementation, release, and close of the IT change is required:""
    validations:
      required: true
  - type: checkboxes
    id: change_intended_use
    attributes:
      label: "**Does the IT change alter the intended use?**" 
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true
  - type: input
    id: Justification
    attributes:
      label: Justification
      description: Why is this change necessary?
      placeholder: Why is this change necessary?
    validations:
      required: true
  - type: checkboxes
    id: Impact
    attributes:
      label: Impact
      description: What is the impact of this change?
      options:
        - label: "Low"
        - label: "Medium"
        - label: "High"
  