name: Review and Approve Pending Deployments

on:
  workflow_dispatch:

jobs:
  review_and_approve:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pending deployments
        id: get_pending_deployments
        run: |
          echo "Retrieving pending deployments..."
          PENDING_DEPLOYMENTS=$(curl -s --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/deployments \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.[] | select(.statuses_url != null) | .id')
          echo "Pending Deployments: $PENDING_DEPLOYMENTS"
          echo "pending_deployments=$(echo "$PENDING_DEPLOYMENTS" | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: debugging output
        run: |
          echo "debug: ${{ steps.get_pending_deployments.outputs.pending_deployments }}"

      - name: Approve pending deployments
        if: steps.get_pending_deployments.outputs.pending_deployments != ''
        run: |
          for DEPLOYMENT_ID in ${{ steps.get_pending_deployments.outputs.pending_deployments }}; do
            echo "Approving deployment ID: $DEPLOYMENT_ID..."
            curl -s --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
              --header "Accept: application/vnd.github.v3+json" \
              --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              --data '{"state": "success", "description": "Approved by GitHub Action", "environment": "test"}'
          done
