name: Dummy Deployment

on:
  workflow_dispatch:

jobs:
  get_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the run_id
        id: echo_run_id
        run: echo "The run_id is ${{ github.run_id }}"
        shell: bash
  approve:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Starting pending deployments
        id: Start_Deployments
        run: echo "Starting pending deployments"
