name: Add comment
on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - closed
jobs:
  add-URS:
    if: github.event.label.name == 'Requirement Specification'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is for Requirement Specification.
            :sparkles: Thank you for your contribution! :sparkles:
  add-DS:
    if: github.event.label.name == 'Design Specification'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: gh issue edit "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          URL: ${{ github.event.issue.html_url }}
          BODY: >
            ${{ github.event.issue.body }}
            ----- appended ------
            This issue is for Design Specification.
            link: ${{ github.event.issue.html_url }} 
            type: ${{ github.event.action }}
            author: ${{ github.event.issue.user.login }}
            number: ${{ github.event.issue.number }}
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
