name: Label PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "this is the link"
      - uses: actions/checkout@main
      - uses: Showoffninja/update-issues-qms@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: needs-review
