name: Label PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  packages: read
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: showoffninja/qms-manual-approval@main
        with:
          secret: ${{ secrets.github.TOKEN }}
          approvers: showoffninja
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ""
          additional-denied-words: ""
      - run: echo "this is the link"
      - uses: actions/checkout@main
      - uses: Showoffninja/update-issues-qms@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: needs-review
