name: Label PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: showoffninja/update-issues-qms@latest
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: needs-review
